# Generated by Django 5.2.4 on 2025-07-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='name',
        ),
        migrations.AddField(
            model_name='shift',
            name='break_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
